codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  range: 90..100
  round: down
  precision: 2
  status:
    project:
      default: off
      unit:
        flags:
          - unit

comment:
  layout: "reach, diff, flags, files"
  behavior: default


flags:
  codecov:
    paths:
      - packages/ChurnZero/
    carryforward: true

ignore:
  - "coverage"
  - "dist"
  - "docs"
  - "node_modules"
  - "out-tsc"
  - "tooling"
  - "packges/**/*.spec.ts"
  - "packges/**/*.mock.ts"
