name: "Main"
on:
  push:
    branches:
      - "main"
env:
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: "List - Test - Lint - Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - run: git fetch --no-tags --prune --depth=50 origin +refs/heads/main:refs/remotes/origin/main

      - name: "Set up Node"
        uses: actions/setup-node@v3
        with:
          node-version: 16
        if: env.SHOULD_RUN == 'true'

      - name: "Restore workspace cache"
        uses: actions/cache@v3
        id: workspace-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-workspace-001-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-workspace-001-

      - name: "Install Dependencies"
        run: yarn install --frozen-lockfile --non-interactive

      - name: "Set NX SHAs"
        uses: nrwl/nx-set-shas@v3
        run: npm ci

      - run: npx nx-cloud start-agent
      - run: npx nx-cloud start-ci-run
      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=build --parallel=3
      - run: npx nx-cloud stop-all-agents

      - name: "Upload coverage results to CodeCov"
        uses: codecov/codecov-action@v3

  agents:
    runs-on: ubuntu-latest
    name: Agent 1
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
