name: "PR"
on: pull_request
env:
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  list_test_lint_build:
    name: "List - Test - Lint - Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - run: git fetch --no-tags --prune --depth=50 origin +refs/heads/main:refs/remotes/origin/main
      - name: "Set SHOULD_RUN flag"
        run: |
          if [[ "${{github.event.head_commit.message}}" =~ (skip\ ci|ci\ skip) ]]; then
            echo "SHOULD_RUN=false" >> $GITHUB_ENV
          else
            echo "SHOULD_RUN=true" >> $GITHUB_ENV
          fi

      - name: "Set up Node"
        uses: actions/setup-node@v3
        with:
          node-version: 16
        if: env.SHOULD_RUN == 'true'

      - name: "Restore workspace cache"
        uses: actions/cache@v3
        id: workspace-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-workspace-001-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-workspace-001-
        if: env.SHOULD_RUN == 'true'

      - name: "Install Dependencies"
        run: yarn install --frozen-lockfile --non-interactive
        if: env.SHOULD_RUN == 'true'

      - name: "List affected"
        run: yarn print-affected --base=origin/main --head=HEAD
        if: env.SHOULD_RUN == 'true'

      - run: npx nx-cloud start-agent
        if: env.SHOULD_RUN == 'true'
      - run: npx nx-cloud start-ci-run
        if: env.SHOULD_RUN == 'true'
      - run: npx nx workspace-lint
        if: env.SHOULD_RUN == 'true'
      - run: npx nx format:check
        if: env.SHOULD_RUN == 'true'
      - run: npx nx affected --target=lint --parallel=3
        if: env.SHOULD_RUN == 'true'
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
        if: env.SHOULD_RUN == 'true'
      - run: npx nx affected --target=build --parallel=3
        if: env.SHOULD_RUN == 'true'
      - run: npx nx-cloud stop-all-agents
        if: env.SHOULD_RUN == 'true'

      - name: "Upload coverage results to CodeCov"
        uses: codecov/codecov-action@v3
        if: env.SHOULD_RUN == 'true'
