name: "Publish"
on:
  push:
    branches:
      - "main"
env:
  GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
  NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
  NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}"
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  #
  # Cancel any workflows that would be duplicated by this run
  #
  cancel_duplicate_runs:
    name: "Cancel Duplicate Runs"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ secrets.GH_TOKEN }}
